esphome:
  name: balcon
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd

  power_save_mode: none
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.0.116
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Balcony Fallback Hotspot"
    password: "nYiYWH6vryl0"

captive_portal:

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret HA_API_pwd

# Example configuration entry
mqtt:
  broker: 192.168.0.113
  username: !secret mqtt_user
  password: !secret mqtt_pwd

# Example configuration entry
web_server:
  port: 80
  auth:
    username: !secret web_server_user
    password: !secret web_server_pwd

ota:

binary_sensor:
  - platform: gpio
    pin: GPIO4
    name: "Relay1 Toggle Button"
    on_press:
      then:
        - switch.turn_off: b_relay1
    on_release:
      then:
        - switch.turn_on: b_relay1

  - platform: gpio
    pin: GPIO5
    name: "Relay2 Toggle Button"
    on_press:
      then:
        - switch.turn_off: b_relay2
    on_release:
      then:
        - switch.turn_on: b_relay2

switch:
  - platform: gpio
    pin:
      number: 2
      inverted: true
    name: "Led Status Balcon"
    id: b_led

  - platform: gpio
    pin:
      number: 0
      inverted: true
    name: "Relay Balcon 1"
    id: b_relay1

  - platform: gpio
    pin:
      number: 16
      inverted: true
    name: "Relay Balcon 2"
    id: b_relay2


