esphome:
  name: co2_sensor
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
  fast_connect: true
  reboot_timeout: 45min
  power_save_mode: none
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.0.109
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 10.10.10.1
    dns2: 1.1.1.1
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "CO2 Fallback Hotspot"
    password: "nYiYWH6vryl0"

captive_portal:

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: !secret HA_API_pwd

# Example configuration entry
#mqtt:
#  broker: 192.168.0.113
#  username: !secret mqtt_user
#  password: !secret mqtt_pwd

# Example configuration entry
web_server:
  port: 80
  auth:
    username: !secret web_server_user
    password: !secret web_server_pwd

ota:

# Example minimal configuration entry TTGO T Display
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: st7789v
    backlight_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    lambda: |-
      it.print(0, 0, id(font), "Hello World!");

# Example configuration entry
uart:
  rx_pin: GPIO26
  tx_pin: GPIO27
  baud_rate: 9600

sensor:
  - platform: mhz19
    co2:
      name: "MH-Z19 CO2 Value"
    temperature:
      name: "MH-Z19 Temperature"
    update_interval: 60s
    automatic_baseline_calibration: false

#Wifi Signal
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
    force_update: true
    
#switch:
#  - platform: gpio
#    name: "on_board_led"
#    pin:
#      number: 2
#      
#  - platform: gpio
#    pin:
#      number: 27
#      inverted: true
#    name: "Relay Living 1"
#    id: l_relay1
#      
#  - platform: gpio
#    pin:
#      number: 26
#      inverted: true
#    name: "Relay Living 2"
#    id: l_relay2
#
#  - platform: gpio
#    pin:
#      number: 25
#      inverted: true
#    name: "Relay Living 3"
#    id: l_relay3
#
#  - platform: gpio
#    pin:
#      number: 33
#      inverted: true
#    name: "Relay Living 4"
#    id: l_relay4
