esphome:
  name: livingroom
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "TP-LINK_8EFC"
  password: "ABCDEFGHIJ"

  power_save_mode: none
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.0.106
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Livingroom Fallback Hotspot"
    password: "nYiYWH6vryl0"

captive_portal:

# Enable logging
logger:
    level: VERY_VERBOSE

# Enable Home Assistant API
api:
  password: "admin"

# Example configuration entry
mqtt:
  broker: 192.168.0.103
  username: admin
  password: admin

# Example configuration entry
web_server:
  port: 80
  auth:
    username: admin
    password: admin

ota:

sensor:
  - platform: dht
    model: DHT22
    pin: GPIO13
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 10s
    
  - platform: adc
    pin: GPIO12
    filters:
      - lambda: |-
          if (x > 3.74) {
            return 0;
          } else if (x < 1.53) {
            return 100;
          } else {
            return (3.74-x) / (3.74-1.53) * 100.0;
          }
    name: "Soil Moisture Level"
    update_interval: 30s
    attenuation: 11db

switch:
  - platform: gpio
    name: "on_board_led"
    pin:
      number: 2
