esphome:
  name: livingroom
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pwd
#  fast_connect: true
  reboot_timeout: 30min
  power_save_mode: none
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.0.106
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 10.10.10.1
    dns2: 1.1.1.1
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Livingroom Fallback Hotspot"
    password: "nYiYWH6vryl0"

captive_portal:

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret HA_API_pwd

# Example configuration entry
#mqtt:
#  broker: 192.168.0.113
#  username: !secret mqtt_user
#  password: !secret mqtt_pwd

# Example configuration entry
web_server:
  port: 80
  auth:
    username: !secret web_server_user
    password: !secret web_server_pwd

ota:

esp32_ble_tracker:

sensor:
  - platform: dht
    model: DHT22
    pin: GPIO13
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 10s
    
#  - platform: adc
#    pin: 32
#    filters:
#      - lambda: |-
#          if (x > 3.7) {
#            return 0;
#          } else if (x < 1.18) {
#            return 100;
#          } else {
#            return (3.7-x) / (3.7-1.18) * 100.0;
#          }
#    unit_of_measurement: "%"
#    name: "Soil Moisture Level"
#    update_interval: 10s
#    attenuation: 11db
    
#  - platform: adc
#    pin: 32
#    unit_of_measurement: "V"
#    name: "Soil Moisture Voltage"
    
#Wifi Signal
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 30s
    force_update: true

#Xiaomi sensors with ATC firmware and Mi Like advertisement    
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:A2:09:D5"
    #bindkey: "eef418daf699a0c188f3bfd17e4565d9"
    temperature:
      name: "ATC Temperature Living"
    humidity:
      name: "ATC Humidity Living"
    battery_level:
      name: "ATC Battery-Level Living"
    
switch:
  - platform: gpio
    name: "on_board_led"
    pin:
      number: 2
      
  - platform: gpio
    pin:
      number: 27
      inverted: true
    name: "Relay Living 1"
    id: l_relay1
    #Safety Automation to self turn off relay after 45s
    on_turn_on:
      then:
        - delay: 45s
        - switch.turn_off: l_relay1
          
  - platform: gpio
    pin:
      number: 26
      inverted: true
    name: "Relay Living 2"
    id: l_relay2
    #Safety Automation to self turn off relay after 45s
    on_turn_on:
      then:
        - delay: 45s
        - switch.turn_off: l_relay2

  - platform: gpio
    pin:
      number: 25
      inverted: true
    name: "Relay Living 3"
    id: l_relay3
    #Safety Automation to self turn off relay after 45s
    on_turn_on:
      then:
        - delay: 45s
        - switch.turn_off: l_relay3
    
  - platform: gpio
    pin:
      number: 33
      inverted: true
    name: "Relay Living 4"
    id: l_relay4
    #Safety Automation to self turn off relay after 45s
    on_turn_on:
      then:
        - delay: 45s
        - switch.turn_off: l_relay4
